[package]
name = "ocieguide"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "ocieguide"


[dependencies]
anyhow = "~1.0.75"
actix-web = "4.4.0"
#actix-web = "4.0.0"
actix-cors = "~0.6.4"
actix-http = "3.4.0"
async-graphql = { git = "https://github.com/async-graphql/async-graphql.git", branch = "master", features = [
    "decimal",
    "tracing",
] }
async-graphql-actix-web = { git = "https://github.com/async-graphql/async-graphql.git", branch = "master" }
bigdecimal = { version = "0.4.1", features = ["serde"] }
chrono = { version = "~0.4.28", default-features = false, features = [
    "alloc",
    "clock",
    "std",
] }
config = "~0.13"
once_cell = "1.18.0"
regex = "1.9.4"
serde = { version = "~1.0.188", features = ["derive"] }
serde-aux = "4.2.0"
serde_json = "~1.0.105"
slab = "~0.4.9"
sqlx = { version = "0.7.1", default-features = false, features = [
    "chrono",
    "bigdecimal",
    "macros",
    "migrate",
    "offline",
    "postgres",
    "runtime-actix-rustls",
    "uuid",
] }
thiserror = "~1.0.47"
tracing = { version = "~0.1.37", features = ["log"] }
tracing-actix-web = "0.7.6"
tracing-bunyan-formatter = "~0.3"
tracing-futures = "~0.2.5"
tracing-log = "~0.1.3"
tracing-subscriber = { version = "~0.3.17", features = [
    "registry",
    "env-filter",
] }
uuid = { version = "1.4.1", features = ["v4", "serde"] }
async-trait = "0.1.73"


[dev-dependencies]
actix-rt = "2.9.0"
claim = "0.5.0"
fake = "2.8.0"
linkify = "0.10.0"
quickcheck = "1.0"
quickcheck_macros = "1.0"
reqwest = { version = "0.11.20", default-features = false, features = [
    "json",
    "rustls-tls",
] }
tokio = { version = "1", features = ["rt", "macros"] }
wiremock = "~0.5.19"
