[package]
name = "ocieguide"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "ocieguide"


[dependencies]
anyhow = "~1.0.0"
#actix-web = "~4.0.1"
actix-web = "4.0.0"
actix-cors = "~0.6.0-beta.10"
actix-http = "3.0.0"
async-graphql = { git = "https://github.com/async-graphql/async-graphql.git", branch = "master", features = [
    "decimal",
    "tracing",
] }
async-graphql-actix-web = { git = "https://github.com/async-graphql/async-graphql.git", branch = "master" }
bigdecimal = { version = "~0.2.2", features = ["serde"] }
chrono = { version = "~0.4.19", default-features = false, features = [
    "alloc",
    "clock",
    "std",
] }
config = "~0.12.0"
once_cell = "~1.9.0"
regex = "~1.5.4"
serde = { version = "~1.0.136", features = ["derive"] }
serde-aux = "~3.0.1"
serde_json = "~1.0.79"
slab = "~0.4.5"
sqlx = { version = "0.5.11", default-features = false, features = [
    "chrono",
    "bigdecimal",
    "macros",
    "migrate",
    "offline",
    "postgres",
    "runtime-actix-rustls",
    "uuid",
] }
thiserror = "~1.0.30"
tracing = { version = "~0.1.31", features = ["log"] }
tracing-actix-web = "~0.5.0"
tracing-bunyan-formatter = "~0.3.2"
tracing-futures = "~0.2.5"
tracing-log = "~0.1.2"
tracing-subscriber = { version = "~0.3.9", features = [
    "registry",
    "env-filter",
] }
uuid = { version = "~0.8.2", features = ["v4", "serde"] }


[dev-dependencies]
actix-rt = "2.6.0"
claim = "0.5.0"
fake = "~2.4.3"
linkify = "0.8.0"
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
reqwest = { version = "~0.11.9", default-features = false, features = [
    "json",
    "rustls-tls",
] }
tokio = { version = "1", features = ["rt", "macros"] }
wiremock = "~0.5.10"
