[package]
name = "ocieguide"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "ocieguide"

[dependencies]
axum = "0.6.18"
http = "0.2.9"
tokio = { version = "1.29.0", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.4.1", features = ["trace", "request-id", "util"] }
tracing = "0.1.37"
tracing-bunyan-formatter = "0.3.7"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
